name: C/C++ CI

on:
  push:
    branches: [ "branchAutomake" ]
  pull_request:
    branches: [ "branchAutomake" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: ./configure
      run: ./configure
    - name: make
      run: make
    - name: tarball
      run: make dist
