name: C/C++ CI

on:
  push:
    branches: [ "branchAutoPackage" ]
  pull_request:
    branches: [ "branchAutoPackage" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: ./configure
      run: ./configure
    - name: make
      run: make
    - name: Install deb to folder
      run: make deb
    - name: Prepare package  
      run: dpkg-deb --build deb
    - name: tarball
      run: make distcheck
