name: C/C++ CI

on:
  push:
    branches: [ "branchHTTPserver" ]
  pull_request:
    branches: [ "branchHTTPserver" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: ./configure
      run: ./configure
    - name: make
      run: make
    - name: Install deb to folder
      run: make deb
    - name: Prepare package  
      run: dpkg-deb --build deb
    - name: tarball
      run: make distcheck
    - name: Autotest
      run: cd ./tests/ && make check
    - name: Login into docker
      run: docker login -u ${{vars.DOCKER_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}
    - name: Build image
      run: docker build --platform=linux/amd64 -t vladikstuk/vladikdonk:amd64 --push .

